build:
	javac BookDepartment.java
	javac Customer.java
	javac Department.java
	javac Item.java
	javac ItemList.java
	javac MusicDepartment.java
	javac Notification.java
	javac Observer.java
	javac ShoppingCart.java
	javac SoftwareDepartment.java
	javac Store.java
	javac Strategy.java
	javac StrategyA.java
	javac StrategyB.java
	javac StrategyC.java
	javac Subject.java
	javac VideoDepartment.java
	javac Visitor.java
	javac WishList.java
	javac Test.java
	
run:
	java Test
clean:
	rm -rf *.class